#-------------------------------
# General Site Settings
baseURL = "http://ghostdogs.photography"
languageCode = "en-us"
title = "Ghostdogs Photography"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 9
theme = ["hugo-shortcode-gallery"]
timeout = 60000
[params]
  logo = "/images/WS.webp" # You can add own logo. For example "/images/logo.png".
  author = "Alan & Tam"
  description = ""
  social = false
  galleryLoadJQuery = true
#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Galleries"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  #[[menu.main]]
  #  identifier = "elements"
  #  name = "Elements"
  #  url = "/elements/"
  #  weight = 5


  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Ghostdog Photography"
    hero__description = "Photos by Alan & Tam"


  #-------------------------------
  # Portfolio Settings
  # [params.portfolio]
   # portfolio__title = "Portfolio"

#  [[params.gallery_item]]
#    image = "/images/Building.jpg"
#    title = "Building"
#    description = "Building - Tam</a>"

  #-------------------------------
  # Subscribe Settings
  #[params.mailchimp]
  #  mailchimp__title = "Get updates and digital art inspiration" # Add your Title
  #  mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  #  mailchimp__input__text = "Email address" # Add your input text.
  #  mailchimp__button__text = "Subscribe" # Add your button text.
  #  mailchimp__bg__color = "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8".

  #-------------------------------
  # Footer Settings
  #[[params.social]]
  #  icon = "ion-logo-twitter"
  #  name = "Twitter"
  #  link = "https://twitter.com"
  #  color = "#55acee"

  #[[params.social]]
  #  icon = "ion-logo-facebook"
  #  name = "Facebook"
  #  link = "https://facebook.com"
  #  color = "#3b5999"

  #[[params.social]]
  #  icon = "ion-logo-pinterest"
  #  name = "Pinterest"
  #  link = "https://pinterest.com"
  #  color = "#bd081c"

  #[[params.social]]
  #  icon = "ion-logo-dribbble"
  #  name = "Dribbble"
  #  link = "https://dribbble.com"
  #  color = "#ea4c89"

  #[[params.social]]
  #  icon = "ion-logo-instagram"
  #  name = "Instagram"
  #  link = "https://instagram.com"
  #  color = "#e4405f"


  #[[params.social]]
  #  icon = "ion-logo-vimeo"
  #  name = "Vimeo"
  #  link = "https://vimeo.com"
  #  color = "#1393cd"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-youtube"
  #   name = "Youtube"
  #   link = "https://youtube.com"
  #   color = "#ff0000"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "alan@ghostdogs.co.uk" # Add your form_id for contant form

    # NOTE
    # Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  #[params.disqus]
  #  disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
